default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5

development:
  <<: *default
  database: totalsub_d
  username: mistress_d
  password: abc123

test:
  <<: *default
  database: totalsub_t
  username: mistress_d
  password: abc123

# On Heroku and other platform providers, you may have a full connection URL
# available as an environment variable. For example:
#
#   DATABASE_URL="postgres://myuser:mypass@localhost/somedatabase"
#
# You can use this database configuration with:
#
#   production:
#     url: <%= ENV['DATABASE_URL'] %>
#
production:
  <<: *default
  database: totalsub
  username: <%= ENV['TOTALSUB_DB_USER'] %>
  password: <%= ENV['TOTALSUB_DB_PASS'] %>
